// India-MCP Metadata - copied from src/metadata for frontend consumption

export const categories = [
  { key: 'finance', label: 'Finance', description: 'Banking, payments, IFSC, UPI, and financial verification.', icon: '💰', color: '#22c55e' },
  { key: 'legal', label: 'Legal', description: 'Court cases, orders, cause lists, and judicial records.', icon: '⚖️', color: '#6366f1' },
  { key: 'compliance', label: 'Compliance', description: 'GST, FSSAI, regulatory filings, and license verification.', icon: '📋', color: '#f59e0b' },
  { key: 'transport', label: 'Transport', description: 'Railways, trains, PNR status, and travel schedules.', icon: '🚆', color: '#3b82f6' },
  { key: 'government', label: 'Government', description: 'Official government portals, records, and public data.', icon: '🏛️', color: '#8b5cf6' },
  { key: 'business', label: 'Business', description: 'Company verification, due diligence, and B2B intelligence.', icon: '🏢', color: '#0ea5e9' },
  { key: 'markets', label: 'Markets', description: 'NSE/BSE equity data, indices, and market analytics.', icon: '📈', color: '#10b981' },
  { key: 'logistics', label: 'Logistics', description: 'Shipment tracking, delivery status, and pincode coverage.', icon: '📦', color: '#f97316' },
  { key: 'identity', label: 'Identity', description: 'Aadhaar, DigiLocker documents, and identity verification.', icon: '🪪', color: '#ec4899' },
] as const

export type CategoryKey = typeof categories[number]['key']

export const servers = [
  {
    key: 'gst',
    name: 'GST',
    binName: 'india-mcp-gst',
    categories: ['compliance', 'finance'] as CategoryKey[],
    description: 'Validate GSTINs, search HSN codes, and calculate taxes.',
    longDescription: "Provides comprehensive access to India's Goods and Services Tax system. Validate any GSTIN for registration status, look up HSN/SAC codes with rates, and compute CGST/SGST/IGST breakdowns. Also surfaces GST filing deadlines for tax compliance workflows.",
    tags: ['compliance', 'government', 'finance', 'verification', 'public-data'],
    stability: 'stable' as const,
    maxRiskLevel: 'low' as const,
    sources: ['GST Portal', 'Offline DB'],
    requiresAuth: false,
    domains: ['taxation', 'compliance', 'business-verification'],
    entryFile: 'gst-server-entry.js',
    toolCount: 5,
    tools: [
      { name: "validate_gstin", description: "Validate a GSTIN and retrieve registration status" },
      { name: "search_hsn_code", description: "Search HSN codes by product keyword" },
      { name: "get_gst_rate_by_hsn", description: "Get GST tax rate for an HSN code" },
      { name: "calculate_gst", description: "Calculate CGST/SGST/IGST from amount and rate" },
      { name: "get_filing_deadline", description: "Get GST filing due dates" },
    ],
  },
  {
    key: 'railways',
    name: 'Railways',
    binName: 'india-mcp-railways',
    categories: ['transport', 'government'] as CategoryKey[],
    description: 'Live train status, PNR enquiry, schedules, and fare calculation.',
    longDescription: 'Access the world\'s fourth-largest railway network. Search trains between stations, check real-time running status, enquire PNR booking status, get station-wise schedules, and calculate fares across travel classes.',
    tags: ['transport', 'government', 'realtime', 'public-data', 'search'],
    stability: 'stable' as const,
    maxRiskLevel: 'medium' as const,
    sources: ['Indian Railways'],
    requiresAuth: false,
    domains: ['transport', 'travel', 'logistics'],
    entryFile: 'railways-server-entry.js',
    toolCount: 7,
    tools: [
      { name: "get_train_status", description: "Live running status of a train" },
      { name: "pnr_status", description: "PNR booking status enquiry" },
      { name: "search_train", description: "Search trains between stations" },
      { name: "get_schedule", description: "Station-wise train schedule" },
      { name: "calculate_fare", description: "Calculate fare between stations" },
      { name: "get_station_info", description: "Get station details by code" },
      { name: "check_seat_availability", description: "Check seat availability" },
    ],
  },
  {
    key: 'rto',
    name: 'RTO',
    binName: 'india-mcp-rto',
    categories: ['transport', 'government', 'compliance'] as CategoryKey[],
    description: 'Vehicle registration details, challan checks, and road tax calculator.',
    longDescription: "Interface with India's Regional Transport Office data. Decode vehicle registration numbers, retrieve ownership and insurance details, check pending challans, calculate road tax liability, and get RTO office information.",
    tags: ['verification', 'government', 'compliance', 'risk-analysis', 'transport'],
    stability: 'stable' as const,
    maxRiskLevel: 'high' as const,
    sources: ['RTO Portal', 'Offline DB'],
    requiresAuth: false,
    domains: ['automotive', 'transport', 'compliance'],
    entryFile: 'rto-server-entry.js',
    toolCount: 6,
    tools: [
      { name: "decode_registration_number", description: "Decode vehicle registration plate" },
      { name: "get_vehicle_info", description: "Get ownership, insurance, fitness details" },
      { name: "check_vehicle_challan", description: "Check pending traffic fines" },
      { name: "calculate_road_tax", description: "Calculate road tax liability" },
      { name: "get_rto_office_info", description: "Get RTO office address and contact" },
      { name: "check_driving_license_status", description: "Verify driving license validity" },
    ],
  },
  {
    key: 'banking',
    name: 'Banking',
    binName: 'india-mcp-banking',
    categories: ['finance', 'business'] as CategoryKey[],
    description: 'IFSC lookups, UPI validation, and bank uptime status.',
    longDescription: 'Core financial infrastructure verification. Look up bank branch details using IFSC codes, validate UPI Virtual Payment Addresses, and check real-time UPI uptime for major Indian banks.',
    tags: ['finance', 'verification', 'realtime', 'public-data'],
    stability: 'stable' as const,
    maxRiskLevel: 'low' as const,
    sources: ['Razorpay IFSC', 'NPCI UPI', 'Offline DB'],
    requiresAuth: false,
    domains: ['payments', 'banking', 'finance'],
    entryFile: 'banking-server-entry.js',
    toolCount: 3,
    tools: [
      { name: "ifsc_lookup", description: "Look up bank branch by IFSC code" },
      { name: "upi_validate", description: "Validate UPI payment address" },
      { name: "bank_uptime", description: "Check real-time UPI uptime" },
    ],
  },
  {
    key: 'stocks',
    name: 'Stocks',
    binName: 'india-mcp-stocks',
    categories: ['markets', 'finance'] as CategoryKey[],
    description: 'Real-time NSE/BSE quotes, indices, historical data, and market status.',
    longDescription: 'Comprehensive Indian equity market access. Fetch real-time stock quotes with automatic NSE → Yahoo Finance fallback, track market indices (NIFTY 50, SENSEX), view historical OHLCV candles, get gainers/losers, monitor IPO pipeline, and check if the market is currently open.',
    tags: ['markets', 'realtime', 'finance', 'risk-analysis', 'search'],
    stability: 'stable' as const,
    maxRiskLevel: 'medium' as const,
    sources: ['NSE', 'BSE', 'Yahoo Finance', 'Offline DB'],
    requiresAuth: false,
    domains: ['equity', 'markets', 'investing', 'fintech'],
    entryFile: 'stocks-server-entry.js',
    toolCount: 6,
    tools: [
      { name: "get_quote", description: "Get real-time stock quote" },
      { name: "get_market_status", description: "Check if market is open/closed" },
      { name: "get_historical_data", description: "Get historical OHLCV data" },
      { name: "search_stocks", description: "Search stocks by name or symbol" },
      { name: "get_index", description: "Get index (NIFTY/SENSEX) value" },
      { name: "get_sector_performance", description: "Compare sector performance" },
    ],
  },
  {
    key: 'ecourts',
    name: 'eCourts',
    binName: 'india-mcp-ecourts',
    categories: ['legal', 'government'] as CategoryKey[],
    description: 'Court cases, hearing history, orders, and daily cause lists.',
    longDescription: "Access the Indian judicial system's public records. Search court cases by number and year, retrieve hearing history, fetch court orders (with PDF links where available), and view daily cause lists for courtroom scheduling. Covers District Courts across all states.",
    tags: ['legal', 'government', 'risk-analysis', 'verification', 'public-data'],
    stability: 'stable' as const,
    maxRiskLevel: 'high' as const,
    sources: ['eCourts Portal'],
    requiresAuth: false,
    domains: ['legal', 'compliance', 'due-diligence'],
    entryFile: 'ecourts-server-entry.js',
    toolCount: 4,
    tools: [
      { name: "search_case", description: "Search cases by case number, party, or advocates" },
      { name: "get_case_status", description: "Get detailed case status and history" },
      { name: "get_causelist", description: "Get daily cause list for a court" },
      { name: "get_case_orders", description: "Get orders/judgments for a case" },
    ],
  },
  {
    key: 'fssai',
    name: 'FSSAI',
    binName: 'india-mcp-fssai',
    categories: ['compliance', 'business', 'government'] as CategoryKey[],
    description: 'Food business license verification and category lookup.',
    longDescription: "Verify India's food safety licensing ecosystem through the FSSAI FOSCOS portal. Look up 14-digit FSSAI licenses for validity, business details, and food categories. Search food businesses by name or state, and check license expiry with days-remaining calculation.",
    tags: ['compliance', 'verification', 'government', 'risk-analysis', 'search'],
    stability: 'stable' as const,
    maxRiskLevel: 'medium' as const,
    sources: ['FSSAI FOSCOS', 'Offline DB'],
    requiresAuth: false,
    domains: ['food-safety', 'compliance', 'business-verification'],
    entryFile: 'fssai-server-entry.js',
    toolCount: 2,
    tools: [
      { name: "verify_fssai_license", description: "Verify FSSAI license/registration number" },
      { name: "search_fssai_by_pincode", description: "Search FSSAI establishments by pincode" },
    ],
  },
  {
    key: 'delhivery',
    name: 'Delhivery',
    binName: 'india-mcp-delhivery',
    categories: ['logistics', 'business'] as CategoryKey[],
    description: 'Shipment tracking, shipping rates, and pincode serviceability.',
    longDescription: "Integrate with Delhivery's logistics platform. Track individual or bulk shipments by AWB number, calculate shipping rates between pincodes, verify delivery serviceability, and retrieve registered pickup locations. Requires a Delhivery API token.",
    tags: ['logistics', 'realtime', 'verification', 'finance'],
    stability: 'stable' as const,
    maxRiskLevel: 'low' as const,
    sources: ['Delhivery API'],
    requiresAuth: true,
    domains: ['logistics', 'ecommerce', 'supply-chain'],
    entryFile: 'delhivery-server-entry.js',
    toolCount: 2,
    tools: [
      { name: "track_shipment", description: "Track shipment by AWB or tracking number" },
      { name: "get_pickup_status", description: "Check pickup request status" },
    ],
  },
  {
    key: 'digilocker',
    name: 'DigiLocker',
    binName: 'india-mcp-digilocker',
    categories: ['identity', 'government'] as CategoryKey[],
    description: 'Government document access and Aadhaar verification via DigiLocker.',
    longDescription: "Access India's official digital document wallet. Generate OAuth 2.0 authorization URLs, exchange auth codes for tokens, list a user's government-issued documents (Aadhaar, PAN, Driving License), fetch individual documents, and verify Aadhaar seeding status. Requires DigiLocker API credentials.",
    tags: ['identity', 'government', 'verification', 'compliance'],
    stability: 'stable' as const,
    maxRiskLevel: 'high' as const,
    sources: ['DigiLocker API'],
    requiresAuth: true,
    domains: ['identity', 'kyc', 'government-documents'],
    entryFile: 'digilocker-server-entry.js',
    toolCount: 2,
    tools: [
      { name: "list_documents", description: "List documents in DigiLocker vault" },
      { name: "pull_document", description: "Pull a document from DigiLocker" },
    ],
  },
] as const

export const workflows = [
  {
    key: 'business_due_diligence',
    name: 'Business Due Diligence',
    description: "Verify a company's legal, tax, and financial legitimacy before onboarding.",
    useCases: ['Vendor onboarding checks', 'B2B partner verification', 'Investor due diligence', 'Loan eligibility assessment'],
    estimatedTime: '30–60 seconds',
    steps: [
      { server: 'gst', tool: 'validate_gstin', description: "Verify the business's GSTIN is active and registered.", required: true },
      { server: 'banking', tool: 'check_vpa_format', description: "Validate the UPI payment address is well-formed.", required: false },
      { server: 'banking', tool: 'get_ifsc_details', description: "Confirm the bank account branch exists via IFSC.", required: false },
      { server: 'fssai', tool: 'verify_fssai_license', description: "Check FSSAI license if the company is in food sector.", required: false },
      { server: 'ecourts', tool: 'search_case', description: "Search for pending litigation using company name.", required: false },
    ],
  },
  {
    key: 'stock_research',
    name: 'Stock Research',
    description: 'Comprehensive equity analysis combining real-time prices, history, and sector context.',
    useCases: ['Investment decision support', 'Portfolio monitoring', 'Market trend analysis', 'Pre-market briefing'],
    estimatedTime: '15–30 seconds',
    steps: [
      { server: 'stocks', tool: 'get_market_status', description: "Check if markets are currently open.", required: true },
      { server: 'stocks', tool: 'get_stock_quote', description: "Fetch real-time price and volume.", required: true },
      { server: 'stocks', tool: 'get_stock_history', description: "Pull historical candle data for trend analysis.", required: false },
      { server: 'stocks', tool: 'get_sector_performance', description: "Compare against sector peers.", required: false },
    ],
  },
  {
    key: 'transport_verification',
    name: 'Transport & Vehicle Verification',
    description: 'Full verification of a vehicle or logistics operator before hire or payment.',
    useCases: ['Fleet onboarding', 'Logistics partner verification', 'Vehicle insurance check', 'Challan compliance review'],
    estimatedTime: '20–45 seconds',
    steps: [
      { server: 'rto', tool: 'decode_registration_number', description: 'Decode the registration plate to extract state and RTO.', required: true },
      { server: 'rto', tool: 'get_vehicle_info', description: 'Fetch full ownership, insurance, and fitness details.', required: true },
      { server: 'rto', tool: 'check_vehicle_challan', description: 'Check for pending traffic fines.', required: true },
    ],
  },
  {
    key: 'legal_compliance',
    name: 'Legal & Regulatory Compliance',
    description: "Check an entity's full regulatory standing across GST, FSSAI, and court records.",
    useCases: ['Regulatory audit preparation', 'Restaurant / food chain compliance', 'Pre-acquisition due diligence', 'NGO or trust verification'],
    estimatedTime: '45–90 seconds',
    steps: [
      { server: 'gst', tool: 'validate_gstin', description: "Confirm GST registration is active.", required: true },
      { server: 'fssai', tool: 'verify_fssai_license', description: "Verify food safety license for F&B businesses.", required: false },
      { server: 'ecourts', tool: 'search_case', description: "Search for active court cases filed against the entity.", required: false },
    ],
  },
] as const

export type Server = typeof servers[number]

export const Metadata = {
  servers,
  categories,
  workflows,
  totalTools: servers.reduce((acc, s) => acc + s.toolCount, 0),
  totalServers: servers.length,
  totalWorkflows: workflows.length,
  totalCategories: categories.length,
}