/**
 * Centralized tool metadata for the entire India-MCP ecosystem.
 * This is the single source of truth for tool discovery, docs generation, and dashboards.
 */

import type { CategoryKey } from './categories.js';

export type RiskLevel = 'low' | 'medium' | 'high';
export type StabilityLevel = 'stable' | 'beta' | 'experimental';
export type DataSource = 'NSE' | 'BSE' | 'Yahoo Finance' | 'GST Portal' | 'Indian Railways' | 'Razorpay IFSC' | 'NPCI' | 'eCourts Portal' | 'FSSAI FOSCOS' | 'Delhivery API' | 'DigiLocker API' | 'RTO Portal' | 'NPCI UPI' | 'Offline DB';
export type ToolTag =
  | 'verification'
  | 'compliance'
  | 'finance'
  | 'legal'
  | 'public-data'
  | 'government'
  | 'realtime'
  | 'risk-analysis'
  | 'search'
  | 'identity'
  | 'logistics'
  | 'markets'
  | 'transport'
  | 'offline'
  | 'business';

export interface ToolExample {
  description: string;
  args: Record<string, unknown>;
  expectedSource?: string;
}

export interface ToolMetadata {
  name: string;
  server: string;
  category: CategoryKey;
  description: string;
  tags: ToolTag[];
  riskLevel: RiskLevel;
  stability: StabilityLevel;
  cacheTTLSeconds: number | null;
  sources: DataSource[];
  requiresAuth: boolean;
  rateLimited: boolean;
  governmentSource: boolean;
  examples: ToolExample[];
  workflows?: string[];
}

export const TOOL_METADATA: ToolMetadata[] = [
  // --- GST ---
  {
    name: 'validate_gstin',
    server: 'gst',
    category: 'compliance',
    description: 'Validate a 15-digit GSTIN and retrieve its registration status and business details.',
    tags: ['verification', 'compliance', 'government', 'public-data'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 3600,
    sources: ['GST Portal'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Verify a GSTIN', args: { gstin: '27AAPFU0939F1ZV' } }],
    workflows: ['business_due_diligence', 'legal_compliance'],
  },
  {
    name: 'search_hsn_code',
    server: 'gst',
    category: 'compliance',
    description: 'Search HSN codes by product description or keyword.',
    tags: ['search', 'compliance', 'finance'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 86400,
    sources: ['GST Portal'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Find HSN for furniture', args: { query: 'furniture' } }],
    workflows: ['legal_compliance'],
  },
  {
    name: 'get_gst_rate_by_hsn',
    server: 'gst',
    category: 'compliance',
    description: 'Get the applicable GST tax rate for a specific HSN code.',
    tags: ['finance', 'compliance', 'government'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 86400,
    sources: ['GST Portal'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Get rate for HSN 9403', args: { hsn: '9403' } }],
    workflows: ['legal_compliance'],
  },
  {
    name: 'calculate_gst',
    server: 'gst',
    category: 'finance',
    description: 'Calculate GST breakdown (CGST, SGST, IGST) for a given amount and rate.',
    tags: ['finance', 'compliance'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: null,
    sources: ['Offline DB'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Calculate 18% GST on ₹1000', args: { amount: 1000, rate: 18 } }],
    workflows: ['business_due_diligence', 'legal_compliance'],
  },
  {
    name: 'get_filing_deadlines',
    server: 'gst',
    category: 'compliance',
    description: 'Get upcoming GST filing deadlines (GSTR-1, GSTR-3B, etc.) for the current month.',
    tags: ['compliance', 'government', 'finance'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 3600,
    sources: ['GST Portal'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Deadlines for April 2024', args: { month: '2024-04' } }],
    workflows: ['legal_compliance'],
  },

  // --- Banking ---
  {
    name: 'get_ifsc_details',
    server: 'banking',
    category: 'finance',
    description: 'Retrieve bank branch details (bank name, address, MICR) using an IFSC code.',
    tags: ['verification', 'finance', 'public-data'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 86400,
    sources: ['Razorpay IFSC'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Look up SBIN0001234', args: { ifsc: 'SBIN0001234' } }],
    workflows: ['business_due_diligence', 'transport_verification'],
  },
  {
    name: 'get_bank_upi_status',
    server: 'banking',
    category: 'finance',
    description: 'Check the current UPI uptime and transaction success rate for a bank.',
    tags: ['finance', 'realtime', 'verification'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 900,
    sources: ['NPCI UPI', 'Offline DB'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Check UPI status for HDFC', args: { bank: 'HDFC' } }],
    workflows: ['business_due_diligence'],
  },
  {
    name: 'check_vpa_format',
    server: 'banking',
    category: 'finance',
    description: 'Validate the format of a UPI Virtual Payment Address (VPA/UPI ID).',
    tags: ['verification', 'finance', 'identity'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: null,
    sources: ['Offline DB'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Validate a UPI ID', args: { vpa: 'user@okaxis' } }],
    workflows: ['business_due_diligence'],
  },

  // --- Stocks ---
  {
    name: 'get_market_status',
    server: 'stocks',
    category: 'markets',
    description: 'Check if the NSE market is currently open or closed, with IST timestamps.',
    tags: ['markets', 'realtime'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 60,
    sources: ['Offline DB'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Check if market is open now', args: {} }],
    workflows: ['stock_research'],
  },
  {
    name: 'get_stock_quote',
    server: 'stocks',
    category: 'markets',
    description: 'Get real-time stock price, change, volume, and 52-week range for an NSE/BSE symbol.',
    tags: ['markets', 'realtime', 'finance'],
    riskLevel: 'medium',
    stability: 'stable',
    cacheTTLSeconds: 15,
    sources: ['NSE', 'Yahoo Finance'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: false,
    examples: [
      { description: 'Get quote for Reliance', args: { symbol: 'RELIANCE' }, expectedSource: 'NSE' },
      { description: 'Get quote for TCS', args: { symbol: 'TCS' } },
    ],
    workflows: ['stock_research'],
  },
  {
    name: 'search_stock',
    server: 'stocks',
    category: 'markets',
    description: 'Search NSE/BSE stocks by company name or partial symbol with offline fallback.',
    tags: ['markets', 'search', 'offline'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 300,
    sources: ['NSE', 'Offline DB'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Search for Tata companies', args: { query: 'Tata' } }],
    workflows: ['stock_research'],
  },
  {
    name: 'get_market_indices',
    server: 'stocks',
    category: 'markets',
    description: 'Get current values of NIFTY 50, SENSEX, NIFTY BANK, and other major indices.',
    tags: ['markets', 'realtime', 'public-data'],
    riskLevel: 'medium',
    stability: 'stable',
    cacheTTLSeconds: 30,
    sources: ['NSE'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: false,
    examples: [{ description: 'Get all major indices', args: {} }],
    workflows: ['stock_research'],
  },
  {
    name: 'get_stock_history',
    server: 'stocks',
    category: 'markets',
    description: 'Fetch historical OHLCV candle data for a stock symbol over a given period.',
    tags: ['markets', 'finance', 'risk-analysis'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 3600,
    sources: ['Yahoo Finance'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Get 3-month history for INFY', args: { symbol: 'INFY', period: '3M' } }],
    workflows: ['stock_research'],
  },
  {
    name: 'get_top_gainers_losers',
    server: 'stocks',
    category: 'markets',
    description: 'Get the top gaining and losing stocks on NSE for the current trading session.',
    tags: ['markets', 'realtime', 'risk-analysis'],
    riskLevel: 'medium',
    stability: 'stable',
    cacheTTLSeconds: 30,
    sources: ['NSE'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: false,
    examples: [{ description: 'Get top 5 gainers and losers', args: { type: 'both', limit: 5 } }],
    workflows: ['stock_research'],
  },
  {
    name: 'get_ipo_status',
    server: 'stocks',
    category: 'markets',
    description: 'Retrieve status and details of upcoming, open, and recently listed NSE/BSE IPOs.',
    tags: ['markets', 'public-data', 'finance'],
    riskLevel: 'low',
    stability: 'beta',
    cacheTTLSeconds: 300,
    sources: ['NSE'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Get all IPOs', args: { status: 'all' } }],
    workflows: ['stock_research'],
  },
  {
    name: 'get_sector_performance',
    server: 'stocks',
    category: 'markets',
    description: 'Get performance metrics for major NIFTY sector indices (IT, Bank, Pharma, Auto, etc.).',
    tags: ['markets', 'realtime', 'risk-analysis'],
    riskLevel: 'medium',
    stability: 'stable',
    cacheTTLSeconds: 60,
    sources: ['NSE', 'Offline DB'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: false,
    examples: [{ description: 'Get all sector performance', args: {} }],
    workflows: ['stock_research'],
  },

  // --- Railways ---
  {
    name: 'get_pnr_status',
    server: 'railways',
    category: 'transport',
    description: 'Check the live booking status and berth assignment for a 10-digit PNR number.',
    tags: ['transport', 'government', 'realtime', 'verification'],
    riskLevel: 'medium',
    stability: 'stable',
    cacheTTLSeconds: 300,
    sources: ['Indian Railways'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: true,
    examples: [{ description: 'Check PNR status', args: { pnr: '1234567890' } }],
    workflows: [],
  },
  {
    name: 'search_trains',
    server: 'railways',
    category: 'transport',
    description: 'Find all trains running between a source and destination station.',
    tags: ['transport', 'search', 'government'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 3600,
    sources: ['Indian Railways'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Trains from NDLS to MMCT', args: { source: 'NDLS', destination: 'MMCT' } }],
    workflows: [],
  },
  {
    name: 'get_train_schedule',
    server: 'railways',
    category: 'transport',
    description: 'Get the complete station-wise timetable for a specific train number.',
    tags: ['transport', 'government', 'public-data'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 86400,
    sources: ['Indian Railways'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Schedule for Rajdhani Express', args: { trainNumber: '12951' } }],
    workflows: [],
  },
  {
    name: 'get_live_status',
    server: 'railways',
    category: 'transport',
    description: 'Get the real-time running status and current location of a train.',
    tags: ['transport', 'realtime', 'government'],
    riskLevel: 'medium',
    stability: 'stable',
    cacheTTLSeconds: 120,
    sources: ['Indian Railways'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: true,
    examples: [{ description: 'Live status of train 12951', args: { trainNumber: '12951' } }],
    workflows: [],
  },
  {
    name: 'get_fare',
    server: 'railways',
    category: 'transport',
    description: 'Calculate ticket fare between two stations for different travel classes.',
    tags: ['transport', 'finance', 'government'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 86400,
    sources: ['Indian Railways'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Fare for 3AC NDLS to MMCT', args: { source: 'NDLS', destination: 'MMCT', trainClass: '3A' } }],
    workflows: [],
  },
  {
    name: 'get_station_info',
    server: 'railways',
    category: 'transport',
    description: 'Get station details including zone, division, and facilities.',
    tags: ['transport', 'government', 'public-data'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 86400,
    sources: ['Indian Railways'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Info for New Delhi station', args: { stationCode: 'NDLS' } }],
    workflows: [],
  },
  {
    name: 'search_station_by_name',
    server: 'railways',
    category: 'transport',
    description: 'Search for Indian railway stations by partial name or city.',
    tags: ['transport', 'search', 'public-data'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 86400,
    sources: ['Indian Railways', 'Offline DB'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Search stations in Mumbai', args: { query: 'Mumbai' } }],
    workflows: [],
  },

  // --- RTO ---
  {
    name: 'decode_registration_number',
    server: 'rto',
    category: 'transport',
    description: 'Decode an Indian vehicle registration number to extract state, RTO, and vehicle class.',
    tags: ['verification', 'transport', 'public-data', 'offline'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: null,
    sources: ['Offline DB'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Decode MH01AB1234', args: { regNumber: 'MH01AB1234' } }],
    workflows: ['transport_verification'],
  },
  {
    name: 'get_vehicle_info',
    server: 'rto',
    category: 'government',
    description: 'Get full vehicle registration details including owner, insurance, and fitness status.',
    tags: ['verification', 'government', 'risk-analysis'],
    riskLevel: 'high',
    stability: 'stable',
    cacheTTLSeconds: 3600,
    sources: ['RTO Portal'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: true,
    examples: [{ description: 'Get vehicle info for MH01AB1234', args: { regNumber: 'MH01AB1234' } }],
    workflows: ['transport_verification'],
  },
  {
    name: 'check_vehicle_challan',
    server: 'rto',
    category: 'compliance',
    description: 'Check for pending traffic challans and fines for a vehicle registration number.',
    tags: ['compliance', 'government', 'risk-analysis', 'legal'],
    riskLevel: 'high',
    stability: 'stable',
    cacheTTLSeconds: 1800,
    sources: ['RTO Portal'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: true,
    examples: [{ description: 'Check challans for MH01AB1234', args: { regNumber: 'MH01AB1234' } }],
    workflows: ['transport_verification'],
  },
  {
    name: 'get_rto_info',
    server: 'rto',
    category: 'government',
    description: 'Get contact details and location of a specific RTO office by code.',
    tags: ['government', 'public-data', 'transport'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 86400,
    sources: ['RTO Portal', 'Offline DB'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Info for MH01 RTO', args: { rtoCode: 'MH01' } }],
    workflows: [],
  },
  {
    name: 'calculate_road_tax',
    server: 'rto',
    category: 'finance',
    description: 'Estimate road tax liability based on vehicle type, age, state, and fuel type.',
    tags: ['finance', 'compliance', 'transport'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: null,
    sources: ['Offline DB'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Road tax for petrol sedan in MH', args: { vehicleType: 'car', fuelType: 'petrol', state: 'Maharashtra', ageYears: 3 } }],
    workflows: ['transport_verification'],
  },
  {
    name: 'get_vehicle_statistics',
    server: 'rto',
    category: 'government',
    description: 'Get aggregate vehicle registration statistics by state or fuel type.',
    tags: ['public-data', 'government', 'risk-analysis'],
    riskLevel: 'low',
    stability: 'beta',
    cacheTTLSeconds: 86400,
    sources: ['RTO Portal', 'Offline DB'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Vehicle stats for Maharashtra', args: { state: 'Maharashtra' } }],
    workflows: [],
  },

  // --- eCourts ---
  {
    name: 'search_court',
    server: 'ecourts',
    category: 'legal',
    description: 'Search for Indian district courts by state and district name.',
    tags: ['legal', 'government', 'search'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 86400,
    sources: ['eCourts Portal'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Find courts in Delhi', args: { state: 'Delhi' } }],
    workflows: ['legal_compliance'],
  },
  {
    name: 'search_case',
    server: 'ecourts',
    category: 'legal',
    description: 'Search court cases by registration number and year of filing.',
    tags: ['legal', 'government', 'verification', 'risk-analysis'],
    riskLevel: 'high',
    stability: 'stable',
    cacheTTLSeconds: 3600,
    sources: ['eCourts Portal'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: true,
    examples: [{ description: 'Search case CS/123/2023', args: { caseNumber: '123', filingYear: '2023' } }],
    workflows: ['legal_compliance', 'business_due_diligence'],
  },
  {
    name: 'get_case_status',
    server: 'ecourts',
    category: 'legal',
    description: 'Get the current hearing stage, judge, and next date for a specific case.',
    tags: ['legal', 'government', 'realtime'],
    riskLevel: 'high',
    stability: 'stable',
    cacheTTLSeconds: 1800,
    sources: ['eCourts Portal'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: true,
    examples: [{ description: 'Get status of a case', args: { caseId: 'EC-123-2023' } }],
    workflows: ['legal_compliance'],
  },
  {
    name: 'get_case_history',
    server: 'ecourts',
    category: 'legal',
    description: 'Retrieve the full chronological hearing history and proceedings for a case.',
    tags: ['legal', 'government', 'risk-analysis'],
    riskLevel: 'high',
    stability: 'stable',
    cacheTTLSeconds: 3600,
    sources: ['eCourts Portal'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: true,
    examples: [{ description: 'History of a case', args: { caseId: 'EC-123-2023' } }],
    workflows: ['legal_compliance', 'business_due_diligence'],
  },
  {
    name: 'get_case_orders',
    server: 'ecourts',
    category: 'legal',
    description: 'Retrieve court orders and judgments, including PDF links where available.',
    tags: ['legal', 'government', 'public-data'],
    riskLevel: 'high',
    stability: 'beta',
    cacheTTLSeconds: 3600,
    sources: ['eCourts Portal'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: true,
    examples: [{ description: 'Orders for a case', args: { caseId: 'EC-123-2023' } }],
    workflows: ['legal_compliance'],
  },
  {
    name: 'get_cause_list',
    server: 'ecourts',
    category: 'legal',
    description: 'Get the daily courtroom hearing schedule (cause list) for a court on a date.',
    tags: ['legal', 'government', 'realtime'],
    riskLevel: 'medium',
    stability: 'stable',
    cacheTTLSeconds: 900,
    sources: ['eCourts Portal'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Cause list for DL01 on 2024-06-15', args: { courtCode: 'DL01', date: '2024-06-15' } }],
    workflows: [],
  },

  // --- FSSAI ---
  {
    name: 'verify_fssai_license',
    server: 'fssai',
    category: 'compliance',
    description: 'Verify a 14-digit FSSAI food license and retrieve business and category details.',
    tags: ['verification', 'compliance', 'government', 'risk-analysis'],
    riskLevel: 'medium',
    stability: 'stable',
    cacheTTLSeconds: 900,
    sources: ['FSSAI FOSCOS'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: true,
    examples: [{ description: 'Verify FSSAI license', args: { licenseNumber: '10012022000001' } }],
    workflows: ['legal_compliance', 'business_due_diligence'],
  },
  {
    name: 'search_food_business',
    server: 'fssai',
    category: 'compliance',
    description: 'Search for food businesses by name or partial keyword.',
    tags: ['search', 'compliance', 'business'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 3600,
    sources: ['FSSAI FOSCOS'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Search for Haldiram', args: { query: 'Haldiram' } }],
    workflows: ['business_due_diligence'],
  },
  {
    name: 'get_food_license_details',
    server: 'fssai',
    category: 'compliance',
    description: 'Get full license metadata including issuing authority, food products, and premises address.',
    tags: ['compliance', 'verification', 'government'],
    riskLevel: 'medium',
    stability: 'stable',
    cacheTTLSeconds: 900,
    sources: ['FSSAI FOSCOS'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: true,
    examples: [{ description: 'Full details for a license', args: { licenseNumber: '10012022000001' } }],
    workflows: ['legal_compliance'],
  },
  {
    name: 'get_fssai_categories',
    server: 'fssai',
    category: 'compliance',
    description: 'List or filter FSSAI food business category codes and descriptions.',
    tags: ['compliance', 'public-data', 'offline'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 86400,
    sources: ['Offline DB'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Get all categories', args: {} }],
    workflows: [],
  },
  {
    name: 'check_license_validity',
    server: 'fssai',
    category: 'compliance',
    description: 'Quickly check if a food license is valid and how many days remain before expiry.',
    tags: ['verification', 'compliance', 'risk-analysis'],
    riskLevel: 'medium',
    stability: 'stable',
    cacheTTLSeconds: 900,
    sources: ['FSSAI FOSCOS'],
    requiresAuth: false,
    rateLimited: true,
    governmentSource: true,
    examples: [{ description: 'Check validity of a license', args: { licenseNumber: '10012022000001' } }],
    workflows: ['legal_compliance', 'business_due_diligence'],
  },
  {
    name: 'search_by_state',
    server: 'fssai',
    category: 'compliance',
    description: 'List food businesses with active licenses in a specific Indian state.',
    tags: ['search', 'compliance', 'government'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 3600,
    sources: ['FSSAI FOSCOS'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Businesses in Maharashtra', args: { state: 'Maharashtra' } }],
    workflows: [],
  },

  // --- Delhivery ---
  {
    name: 'track_shipment',
    server: 'delhivery',
    category: 'logistics',
    description: 'Track a Delhivery shipment in real-time by waybill (AWB) number.',
    tags: ['logistics', 'realtime', 'verification'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 300,
    sources: ['Delhivery API'],
    requiresAuth: true,
    rateLimited: true,
    governmentSource: false,
    examples: [{ description: 'Track AWB 1234567890', args: { waybill: '1234567890' } }],
    workflows: [],
  },
  {
    name: 'get_shipping_rate',
    server: 'delhivery',
    category: 'logistics',
    description: 'Calculate shipping rates for a package between two pincodes.',
    tags: ['logistics', 'finance'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 3600,
    sources: ['Delhivery API'],
    requiresAuth: true,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Rate from 110001 to 400001', args: { origin: '110001', destination: '400001', weight: 1 } }],
    workflows: [],
  },
  {
    name: 'check_serviceability',
    server: 'delhivery',
    category: 'logistics',
    description: 'Check if a pincode is serviceable by Delhivery for delivery.',
    tags: ['logistics', 'verification'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 86400,
    sources: ['Delhivery API'],
    requiresAuth: true,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Check serviceability for 400001', args: { pincode: '400001' } }],
    workflows: [],
  },
  {
    name: 'track_multiple_shipments',
    server: 'delhivery',
    category: 'logistics',
    description: 'Track multiple Delhivery shipments in a single API call.',
    tags: ['logistics', 'realtime'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 300,
    sources: ['Delhivery API'],
    requiresAuth: true,
    rateLimited: true,
    governmentSource: false,
    examples: [{ description: 'Track multiple AWBs', args: { waybills: ['123', '456'] } }],
    workflows: [],
  },
  {
    name: 'get_pickup_locations',
    server: 'delhivery',
    category: 'logistics',
    description: 'Retrieve registered pickup location addresses for a Delhivery account.',
    tags: ['logistics', 'public-data'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: 3600,
    sources: ['Delhivery API'],
    requiresAuth: true,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Get pickup locations', args: {} }],
    workflows: [],
  },
  {
    name: 'parse_delivery_status',
    server: 'delhivery',
    category: 'logistics',
    description: 'Parse and normalize a raw Delhivery status string into a structured format.',
    tags: ['logistics', 'offline'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: null,
    sources: ['Offline DB'],
    requiresAuth: false,
    rateLimited: false,
    governmentSource: false,
    examples: [{ description: 'Parse "Delivered to customer"', args: { status: 'Delivered to customer' } }],
    workflows: [],
  },

  // --- DigiLocker ---
  {
    name: 'get_oauth_url',
    server: 'digilocker',
    category: 'identity',
    description: 'Generate a DigiLocker OAuth 2.0 authorization URL to initiate user login.',
    tags: ['identity', 'government', 'verification'],
    riskLevel: 'low',
    stability: 'stable',
    cacheTTLSeconds: null,
    sources: ['DigiLocker API'],
    requiresAuth: true,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Get OAuth URL', args: { redirectUri: 'https://myapp.in/callback' } }],
    workflows: [],
  },
  {
    name: 'exchange_auth_code',
    server: 'digilocker',
    category: 'identity',
    description: 'Exchange a DigiLocker authorization code for an access token.',
    tags: ['identity', 'government'],
    riskLevel: 'medium',
    stability: 'stable',
    cacheTTLSeconds: null,
    sources: ['DigiLocker API'],
    requiresAuth: true,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'Exchange auth code', args: { code: 'auth_code_here', redirectUri: 'https://myapp.in/callback' } }],
    workflows: [],
  },
  {
    name: 'list_issued_documents',
    server: 'digilocker',
    category: 'identity',
    description: 'List all government documents issued to a user in their DigiLocker account.',
    tags: ['identity', 'government', 'public-data'],
    riskLevel: 'medium',
    stability: 'stable',
    cacheTTLSeconds: 3600,
    sources: ['DigiLocker API'],
    requiresAuth: true,
    rateLimited: false,
    governmentSource: true,
    examples: [{ description: 'List documents for a user', args: { accessToken: 'token_here' } }],
    workflows: [],
  },
  {
    name: 'get_document',
    server: 'digilocker',
    category: 'identity',
    description: 'Fetch and download a specific government document from DigiLocker.',
    tags: ['identity', 'government', 'verification'],
    riskLevel: 'high',
    stability: 'stable',
    cacheTTLSeconds: null,
    sources: ['DigiLocker API'],
    requiresAuth: true,
    rateLimited: true,
    governmentSource: true,
    examples: [{ description: 'Fetch Aadhaar document', args: { accessToken: 'token_here', documentType: 'ADHAR' } }],
    workflows: [],
  },
  {
    name: 'verify_aadhaar_seeding',
    server: 'digilocker',
    category: 'identity',
    description: 'Verify whether a user\'s Aadhaar number is seeded (linked) in their DigiLocker account.',
    tags: ['identity', 'verification', 'government', 'compliance'],
    riskLevel: 'high',
    stability: 'stable',
    cacheTTLSeconds: null,
    sources: ['DigiLocker API'],
    requiresAuth: true,
    rateLimited: true,
    governmentSource: true,
    examples: [{ description: 'Check Aadhaar seeding', args: { accessToken: 'token_here' } }],
    workflows: [],
  },
];

// --- Lookup helpers ---

export function getToolsByServer(server: string): ToolMetadata[] {
  return TOOL_METADATA.filter((t) => t.server === server);
}

export function getToolsByCategory(category: CategoryKey): ToolMetadata[] {
  return TOOL_METADATA.filter((t) => t.category === category);
}

export function getToolsByTag(tag: ToolTag): ToolMetadata[] {
  return TOOL_METADATA.filter((t) => t.tags.includes(tag));
}

export function getToolsByRisk(level: RiskLevel): ToolMetadata[] {
  return TOOL_METADATA.filter((t) => t.riskLevel === level);
}

export function findTool(name: string): ToolMetadata | undefined {
  return TOOL_METADATA.find((t) => t.name === name);
}
